### ISSUE TITLE
Extra parentheses cause statement not to be completely parsed

### ISSUE THREAD

**Issue by homesar** [bruce-dunwiddie/tsql-parser#19]
string query = "SELECT ((A/B)-1) FROM SomeTable";
    var statement = TSQLStatementReader.ParseStatements(query).First() as TSQLSelectStatement;

The extra parentheses in the query causes the engine to not parse anything beyond the last character before the final right paren:

    type: Keyword, value: SELECT
    type: Character, value: (
    type: Character, value: (
    type: Identifier, value: A
    type: Operator, value: /
    type: Identifier, value: B
    type: Character, value: )
    type: Operator, value: -
    type: NumericLiteral, value: 1

**Comment by bruce-dunwiddie** [comment]
Ok. I'll verify that I can reproduce and see if I can get a new release out within a few days, if you want to watch for it.

**Comment by bruce-dunwiddie** [comment]
I've verified that it is an issue. It's currently parsing it into a 2nd statement for some reason. As a workaround, if you only want the tokens, you can use TSQLTokenizer.ParseTokens instead of TSQLStatementReader, until the issue is resolved.

Thank you for reporting the issue.

**Comment by bruce-dunwiddie** [comment]
New version released, v1.2.2, https://www.nuget.org/packages/TSQL.Parser/1.2.2.
