### ISSUE TITLE
"Full T-SQL implementation" only being able to parse select statements?

### ISSUE THREAD

**Issue by AndersBillLinden** [bruce-dunwiddie/tsql-parser#29]
I want to be able to parse anything that the sql server accepts as input.

This library seems to parse select statements and no other type of queries (correct me if I am wrong), so I am bit curious about the documentation reading "Full T-SQL implementation".

**Comment by bruce-dunwiddie** [comment]
The tokenizer, https://github.com/bruce-dunwiddie/tsql-parser/blob/master/TSQL_Parser/TSQL_Parser/TSQLTokenizer.cs , recognizes, identifies, and categorizes all TSQL keywords. The statement parser is built on top of the tokenizer, and yes, it only currently builds up select statements from the tokens returned by the tokenizer.

It is unlikely that the scope of this parser will ever include statement parsers for all possible statements in the TSQL language. If you're looking for that level of compatibility, then I would suggest the parser library from Microsoft, https://docs.microsoft.com/en-us/dotnet/api/microsoft.sqlserver.transactsql.scriptdom.tsqlparser?view=sqlserver-2016 . It has the full compatibility that you're looking for, but is very slow and does not have the friendliest interface.

**Comment by AndersBillLinden** [comment]
I have used it, but it comes with SQL Server. I would prefer an open source variant, if there is anyone.
