### ISSUE TITLE
CASE clause causing parsing into two statements?

### ISSUE THREAD

**Issue by pdeffendol** [bruce-dunwiddie/tsql-parser#30]
I'm getting a query parsed into two statements with the following SQL (simplified from my real query):

```sql
SELECT a.*
FROM a JOIN b
  ON a.id=b.id
  AND CASE WHEN IsNull(a.flag, 0) = 1 THEN IsNull(a.flag2, 0) ELSE 1 END = 1
WHERE	a.id=@id
```

The first statement's last token is the "AND".

Maybe it's not sure how to handle CASE?

**Comment by bruce-dunwiddie** [comment]
Thank you very much for reporting the issue.

I will see if I can reproduce and hopefully resolve within the next week or so.

Bruce Dunwiddie

**Comment by bruce-dunwiddie** [comment]
https://www.nuget.org/packages/TSQL.Parser/1.2.5
