### ISSUE TITLE
Can you directly parse the field name, table name, field type in the SQL statement?

### ISSUE THREAD

**Issue by jyf1997** [bruce-dunwiddie/tsql-parser#42]
Can I let the computer directly list the table name, field name, and field type?

**Comment by bruce-dunwiddie** [comment]
This functionality does not yet exist in the parser.

**Comment by jyf1997** [comment]
> 解析器中尚不存在此功能。

Can you give me some advice in this regard?

**Comment by bruce-dunwiddie** [comment]
I have never attempted this. It looks like the product at sqlparser.com says it has this functionality.

**Comment by jyf1997** [comment]
They are group of businessmen, not technology lovers.

**Comment by bruce-dunwiddie** [comment]
Feel free to create a fork and start adding the necessary functionality to submit back to the library:

- Connect to a database and query out all objects from the database that could be referenced from the SQL statement. (This is the easy part with lots of examples)
- Write logic to match the TSQLIdentifier tokens to the available object names from the database, handling one, two, three, and four part identifiers. (This is the hard part and I don't know of any good examples)
- Expand the parser logic to handle Update statements, along with other types of SQL statements you would like handled. (This is the tedious part)

**Comment by jyf1997** [comment]
Thank you for your guidance and sharing.
