### ISSUE TITLE
Incomplete Token Parsing Logic

### ISSUE THREAD

**Issue by GilesBathgate** [bruce-dunwiddie/tsql-parser#44]
Various test cases crash the tokenizer:

`"\""`,`"\'"`,`"SELECT * FROM Foo WHERE name='"`

https://dotnetfiddle.net/as403g

**Comment by bruce-dunwiddie** [comment]
Thank you for letting me know.

An unhandled exception is obviously not the correct logic here, but what would be your expectation of the parser to return for incomplete TSQL fragments? Should it throw a custom exception message stating it encountered an unexpected end of statement?

**Comment by GilesBathgate** [comment]
For my usage, I am just trying to find SQL fragments in a VS Code Analyzer. I would need it to return an ErrorToken or IncompleteToken or something like that.

I understand that it's probably desirable to throw an exception for other usage scenarios, but I'd prefer the an ErrorToken as the an exception is essentially what it does already, albeit with an ArgumentOutOfRangeException instead of something specific.

**Comment by GilesBathgate** [comment]
![analyzer](https://user-images.githubusercontent.com/444143/61231229-a37bbc00-a723-11e9-83ee-0fe81e3625a5.gif)
Here is an example of what I am trying to do.

**Comment by bruce-dunwiddie** [comment]
Interesting usage.

It may be a week or two before I code in something better for this, buried in a few other things at the moment.

So far, I've found that the same situation can happen from string literals, bracketed identifiers, and multiline comments, but the current handling is different between them.

I'm probably going to go with "IncompleteToken" and most likely subclass it for the three different situations.

**Comment by bruce-dunwiddie** [comment]
https://github.com/bruce-dunwiddie/tsql-parser/releases/tag/v1.2.7

**Comment by bruce-dunwiddie** [comment]
https://www.nuget.org/packages/TSQL.Parser/1.2.7

**Comment by bruce-dunwiddie** [comment]
@GilesBathgate , let me know what you think. And if anyone else finds other situations I'm not covering, let me know.

**Comment by GilesBathgate** [comment]
Yes, this is very cool. It's already much better since I don't have to catch exceptions when parsing SQL fragments. However, I am wondering how difficult it would be to make a further improvement, that would allow me to parse "follow on" fragments starting with an incomplete token, i.e:

`' SELECT`

Since there is no closing quote I'd expect the parser to mark the first character as an IncompleteString, and continue passing the rest of the SQL as though the tokenizer was in its initial state.

https://dotnetfiddle.net/rbOnT2

**Comment by GilesBathgate** [comment]
Some highlighters treat `' SELECT` as an error followed by SQL, and some treat the whole fragment as an unclosed string token, so maybe what I am proposing should be optional?

Here are some highlighters that do:
http://hilite.me/
http://pygments.org/demo/6855963/
https://andrewsun.com/tools/syntax-highlighter/
https://pinetools.com/syntax-highlighter

Here are some that don't:
https://highlight.hohli.com/index.php
https://quickhighlighter.com/code-syntax-highlighter.php

**Comment by bruce-dunwiddie** [comment]
The parser is currently top down, because T-SQL is made to be top down parsed, by starting with an action word, because it's much simpler to implement that way. I have a suspicion that the parsers that are seeing these as two separate tokens are some variation of a bottom up parser. 

I do not currently see how I would parse it the other way without completely restructuring the parser. 

And I think you would probably be the only one who would understand the optional feature.

**Comment by GilesBathgate** [comment]
I will see if I can make a merge request, which doesn't involve a complete restructure. I think the feature is quite common in parsers that can do error recovery: https://www.gnu.org/software/bison/manual/html_node/Error-Recovery.html
