### ISSUE TITLE
Need TSQLUpdateStatementParser

### ISSUE THREAD

**Issue by quyenbc** [bruce-dunwiddie/tsql-parser#5]
Dear Bruce,
How can I use TSQLUpdateStatementParser?

**Comment by bruce-dunwiddie** [comment]
Unfortunately you can't right now. I have not yet implemented it.

**Comment by bruce-dunwiddie** [comment]
[Initial UPDATE statement functionality.](https://github.com/bruce-dunwiddie/tsql-parser/commit/140f0cc522cafa1d0dd9de5eb28fc912e9811533)
