### ISSUE TITLE
How to parse sql with "insert into“?

### ISSUE THREAD

**Issue by polei** [bruce-dunwiddie/tsql-parser#55]
``` cs
var arr =  TSQLStatementReader.ParseStatements(@"
INSERT into table (id,name) 
values ('aa','bb')");
```

However, I get the `TSQL.Statements.TSQLUnknownStatement`.

**Comment by bruce-dunwiddie** [comment]
The only full statement parser that has been implemented so far is for SELECT. For other statements, like INSERT, you can use the TSQLTokenizer to parse out the individual components, https://github.com/bruce-dunwiddie/tsql-parser/wiki/TSQL-Parser-Code-Samples .
