### ISSUE TITLE
It's cannot properly resolve the union syntax

### ISSUE THREAD

**Issue by pccai** [bruce-dunwiddie/tsql-parser#56]
select * from tab1 where id in(select id from stu where tp=1)
union
select * from tab2 where id in(select id from stu where tp =2)

tks.

**Comment by pccai** [comment]
select * from tab1 where id in(select id from stu where tp=1)
union
select * from tab1 where id in(select id from stu where tp =2)

**Comment by bruce-dunwiddie** [comment]
Interesting.

I'm assuming you're using the TSQLStatementReader?

What is it returning that is not correct?

I will set up a test and see if I can see something that doesn't look right.

**Comment by pccai** [comment]
![image](https://user-images.githubusercontent.com/2232794/71544283-39489200-29b8-11ea-9a6f-efce457f2d3e.png)
@bruce-dunwiddie ,tks.

**Comment by bruce-dunwiddie** [comment]
As of v1.3, UNION/UNION ALL/INTERSECT/EXCEPT are all available through the SetOperator property of a TSQLSelectStatement object.

It requires a little more complicated logic to show all the various tokens under their correct section, and it can go many levels deep.

Please see this Fiddle, https://dotnetfiddle.net/0BgaCM , for a more advanced code example.

In typing up the code example, I did find that it is not currently very straightforward to determine which kind of set operator is being used, so I may expose some new properties in the future to make that easier to access.
