### ISSUE TITLE
Question - Create Table Discussion

### ISSUE THREAD

**Issue by int3rrupt** [bruce-dunwiddie/tsql-parser#60]
Hey Bruce,

I'm looking into tackling the CREATE TABLE statement. Could you provide some guidance as to how you would like to handle this for TSQL.Parser?
**TSQLCreateStatement**
vs
**TSQLCreateTableStatement**/**TSQLCreateDatabaseStatement**/**TSQLCreateUserStatement**/**etc.**
I think the latter would be easier to implement but would mean many more classes.

**Comment by bruce-dunwiddie** [comment]
I try to look at it from the user's perspective, and I think someone coming to use the parser would expect the separate classes. I also don't see much that would be shared across the classes, so I don't think any inheritance will be beneficial. So I say just go down the TSQLCreateTableStatement path.

**Comment by int3rrupt** [comment]
Great, thanks for your input.
