### ISSUE TITLE
Parsing case statement

### ISSUE THREAD

**Issue by Guaro89** [bruce-dunwiddie/tsql-parser#67]
Hi, 
when I try to parse sintax like "case when then end" it will return me "case case when then".

**Comment by bruce-dunwiddie** [comment]
Ok, I'll look into and see how it can be improved.

You're saying however that you're trying to parse invalid syntax, that is missing the actual boolean expressions?

**Comment by Guaro89** [comment]
Hi
I ve posted just an example of syntax

I m trying to parse select case when abi = '03654' then 0 else 1 end as abi

Parsing return me select case case when abi = '03654' then 0 else 1 as abi

Thanks you

Il sab 25 apr 2020, 21:18 Bruce Dunwiddie <notifications@github.com> ha
scritto:

**Comment by bruce-dunwiddie** [comment]
Interesting. I know there was a similar issue a few versions back several months ago, so you might just want to check that you're using a recent version, but I'll assume you are, so I'll find out the problem.

I would hope I can find a solution and get a new release out in the next couple of days.

**Comment by Guaro89** [comment]
Hi
Yes I ve just downloaded it yesterday from nuget

Thanks

Il sab 25 apr 2020, 21:27 Bruce Dunwiddie <notifications@github.com> ha
scritto:

**Comment by bruce-dunwiddie** [comment]
Thank you for letting me know about this one. Should be fixed now.

https://www.nuget.org/packages/TSQL.Parser/1.5.1

**Comment by Guaro89** [comment]
Hi
I confirm that now it's ok :-)

thank you

Il giorno dom 26 apr 2020 alle ore 01:20 Bruce Dunwiddie <
notifications@github.com> ha scritto:
