### ISSUE TITLE
Version 2.0  ParseStatements method for string causes NullReference exception

### ISSUE THREAD

**Issue by dzhukovski** [bruce-dunwiddie/tsql-parser#86]
This line of code causing null reference exception but was working well in prev version:

TSQLStatementReader.ParseStatements("SELECT COUNT(*) as count FROM sqlite_master");

**Comment by bruce-dunwiddie** [comment]
Ok. Thank you for the bug report and reproduction.

I unfortunately figured that there had to still be some use cases that I'd missed with the new column level parsing, but at some point had to throw it out into the wild to find them.

You can pin to the previous version for now, and I'll try to fix and publish a new version within a week or so.

**Comment by bruce-dunwiddie** [comment]
Issue resolved in latest version. Please let me know of anything else that comes up.

https://www.nuget.org/packages/TSQL.Parser/2.0.1
