### ISSUE TITLE
Missing ‘AS’ in a CAST function

### ISSUE THREAD

**Issue by cptb** [bruce-dunwiddie/tsql-parser#89]
Hi Bruce,
Using version 2.0.1, I am trying to parse SELECT CAST(123.45 AS INT). The parser seems to drop the AS in the middle. Below is what I got from my tester app.
Input SQL: SELECT CAST(123.45 AS INT)
Output from my tester app:
```
Statement 1:  SELECT CAST ( 123.45 INT )
        Token type: Keyword     Text: SELECT
        Token type: Identifier  Text: CAST
        Token type: Character   Text: (
        Token type: NumericLiteral      Text: 123.45
        Token type: Identifier  Text: INT
        Token type: Character   Text: )
```

In the previous version 1.5.3, 'AS' was still kept as a keyword.

Could you please look at this issue?
Thank you very much again.

**Comment by bruce-dunwiddie** [comment]
Thank you very much for posting this. I'll verify that I can reproduce the issue, and hopefully it's a simple fix. The latest version does full contextually aware parsing instead of the previous generic "read until stop word", so unfortunately it opened up a lot of possibilities for bugs.

**Comment by bruce-dunwiddie** [comment]
I've been able to reproduce the issue.

And of course, the issue is a little complicated, and exists because I don't currently have any logical structure for handling/naming a function argument expression formatted like "XYZ AS [Type]", because this is the only place in the language where this construct exists.

So I'll have to come up with a name for this kind of expression, and then add in logic that looks for it.

Working on it...

**Comment by cptb** [comment]
Thank you very much, Bruce. We have been using this wonderful tool primarily for separating scripts into sections. I thank you again for providing such a useful utility.

**Comment by cptb** [comment]
> I've been able to reproduce the issue.
> 
> And of course, the issue is a little complicated, and exists because I don't currently have any logical structure for handling/naming a function argument expression formatted like "XYZ AS [Type]", because this is the only place in the language where this construct exists.
> 
> So I'll have to come up with a name for this kind of expression, and then add in logic that looks for it.
> 
> Working on it...

Thank you very much, Bruce. We have been using this wonderful tool primarily for separating scripts into sections. I thank you again for providing such a useful utility.

**Comment by bruce-dunwiddie** [comment]
I've released a new version with this fixed.

https://www.nuget.org/packages/TSQL.Parser/2.1.0

https://dotnetfiddle.net/CH2Hw3 shows the new version functionality.

Please continue to send me any issues or feedback you have while using the library. I appreciate the information.

**Comment by cptb** [comment]
> I've released a new version with this fixed.
> 
> https://www.nuget.org/packages/TSQL.Parser/2.1.0
> 
> https://dotnetfiddle.net/CH2Hw3 shows the new version functionality.
> 
> Please continue to send me any issues or feedback you have while using the library. I appreciate the information.

Thank you very much for this. Sorry I did not reply promptly. I have been using the updated version and CAST working greatly now.
